package com.hadef.sakani.domain.value;

import lombok.Getter;

@Getter
public enum FailureEnum {
    STUDENT_NOT_FOUND(1),
    FAILED_TO_SIGNUP(2),
    FAILED_TO_LOGIN(3),
    FAILED_TO_CREATE(4),
    FAILED_TO_CREATE_PROJECT(1001),
    FAILED_TO_CREATE_PROJECT_DUE_TO_DUPLICATE_SLUG_TITLE(1002),
    ERROR_IN_PROJECT_ID(1003),
    ERROR_IN_PROJECT_SLUG_TITLE(1004),
    PROJECT_NOT_FOUND(1005),
    FAILED_IN_UPDATE_PROJECT(1006),
    FAILED_TO_CREATE_PROJECT_TYPE(2001),
    FAILED_TO_CREATE_PROJECT_TYPE_DUE_TO_DUPLICATE_SLUG_TITLE(2002),
    ERROR_IN_PROJECT_TYPE_ID(2003),
    ERROR_IN_PROJECT_TYPE_SLUG_TITLE(2004),
    PROJECT_TYPE_NOT_FOUND(2005),
    FAILED_IN_UPDATE_PROJECT_TYPE(2006),
    FAILED_TO_CREATE_PROJECT_CLASSIFICATION(3001),
    FAILED_TO_CREATE_PROJECT_CLASSIFICATION_DUE_TO_DUPLICATE_SLUG_TITLE(3002),
    ERROR_IN_PROJECT_CLASSIFICATION_ID(3003),
    ERROR_IN_PROJECT_CLASSIFICATION_SLUG_TITLE(3004),
    PROJECT_CLASSIFICATION_NOT_FOUND(3005),
    FAILED_IN_UPDATE_PROJECT_CLASSIFICATION(3006);
    private final int code;

    FailureEnum(int code) {
        this.code = code;
    }
}
