server:
    port: 8083
spring:
    jpa:
        properties:
            hibernate:
                jdbc:
                    batch_size: '30'
        show-sql: false

    main:
        allow-circular-references: true
    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
    profiles:
        active: test
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
    application:
        name: masakin
client:
    url: http://localhost:4200

jwt:
    secret: 8fhgeigayuf64oq8ltw36pi84wl87trf8afpw7ty934t7fwaeGTFyugfldlsjfdglja
